### ISSUE TITLE
loaf-0.10.0/lib/loaf/controller_extensions.rb:13: warning: method redefined; discarding old _breadcrumbs

### ISSUE THREAD

**Issue by brendon** [piotrmurach/loaf#48] opened 2021-05-03 23:52 UTC
The following line is triggering a warning in Ruby 2.7

https://github.com/piotrmurach/loaf/blob/27b508c813f0dd32ce15c8b01f5a94550ee1ebc0/lib/loaf/controller_extensions.rb#L13

Not sure if it's worth fixing? :)

```
gems/2.7.0/gems/loaf-0.10.0/lib/loaf/controller_extensions.rb:13: warning: method redefined; discarding old _breadcrumbs
gems/2.7.0/gems/loaf-0.10.0/lib/loaf/controller_extensions.rb:13: warning: previous definition of _breadcrumbs was here
```

**Comment by piotrmurach** [comment] 2021-05-31 11:48
Hi Brendon,

Thanks for reporting this issue.

I cannot verify this problem. Using `helper_method` shouldn't trigger method redefinition. It's also been there since day one. Running tests against Ruby 2.7 and 3.0 doesn't show any warnings. Are you sure that there isn't some other method from another gem or someplace that triggers this redefinition? Can you replicate this in a bare-bones Rails application?

**Comment by brendon** [comment] 2021-05-31 20:53
Hi @piotrmurach, my guess is that this module is being included twice for some reason, thus it's overwriting the method?

I see in your code you're only including the module once, so maybe something in my code is kicking this off twice? Pretty strange.

On my end I don't get the method overwrite but I do get some other warnings that might need looking at:

```
❯ RUBYOPT="-W2" rake
/Users/brendon/.rbenv/versions/2.7.3/bin/ruby -I/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.3/lib:/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-support-3.9.4/lib /Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.3/exe/rspec --pattern spec/\{unit,integration\}\{,/\*/\*\*\}/\*_spec.rb
/Users/brendon/Projects/loaf/spec/rails_app/config/application.rb:9: warning: `*' interpreted as argument prefix
/Users/brendon/Projects/loaf/spec/rails_app/config/boot.rb:4: warning: File.exists? is a deprecated name, use File.exist? instead
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.9.4/lib/rspec/matchers/dsl.rb:74: warning: method redefined; discarding old exist
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.9.4/lib/rspec/matchers.rb:596: warning: previous definition of exist was here

Randomized with seed 25110
....../Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/node/matchers.rb:676: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/node/matchers.rb:852: warning: The called method `_verify_text' is defined here
..../Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/session.rb:751: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/node/matchers.rb:38: warning: The called method `has_selector?' is defined here
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/node/matchers.rb:835: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/node/matchers.rb:861: warning: The called method `_set_query_session_options' is defined here
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/node/matchers.rb:836: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/queries/selector_query.rb:14: warning: The called method `initialize' is defined here
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/rack_test/node.rb:128: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/brendon/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/rack_test/node.rb:118: warning: The called method `unchecked_find_css' is defined here
...................................................

Top 2 slowest examples (0.06023 seconds, 33.0% of total time):
  breadcrumbs trail adds breadcrumb in view with path variable
    0.0368 seconds ./spec/integration/breadcrumb_trail_spec.rb:36
  Loaf::Configuration yields configuration
    0.02343 seconds ./spec/unit/configuration_spec.rb:26

Top 2 slowest example groups:
  breadcrumbs trail
    0.01203 seconds average (0.0842 seconds / 7 examples) ./spec/integration/breadcrumb_trail_spec.rb:3
  Loaf::Configuration
    0.00939 seconds average (0.03757 seconds / 4 examples) ./spec/unit/configuration_spec.rb:3

Finished in 0.18236 seconds (files took 1.7 seconds to load)
61 examples, 0 failures

Randomized with seed 25110
```

I'll further investigate what's doing the double loading for me :)

**Comment by brendon** [comment] 2021-05-31 21:04
Just a thought; I use engines in my rails app. Perhaps this happens due to that? I'll let you know if I find out more :)

**Comment by piotrmurach** [comment] 2021-07-12 20:11
@brendon I'm closing this as this issue hasn't been verified to be caused by the gem itself.

**Closed as completed by piotrmurach** 2021-07-12 20:11 UTC
Labels: Bug

**Comment by brendon** [comment] 2021-07-13 02:14
All good @piotrmurach :)
